export interface Ingredient {
  id: string;
  name: string;
  servingSize: string; // e.g., "100g", "1 cup", "1 piece"
  calories: number;
  protein: number; // grams
  carbs: number; // grams
  fats: number; // grams
}

export const commonIngredients: Ingredient[] = [
  // Proteins
  {
    id: "chicken-breast",
    name: "Chicken Breast",
    servingSize: "100g",
    calories: 165,
    protein: 31,
    carbs: 0,
    fats: 3.6,
  },
  {
    id: "ground-beef",
    name: "Ground Beef",
    servingSize: "100g",
    calories: 250,
    protein: 26,
    carbs: 0,
    fats: 15,
  },
  {
    id: "salmon",
    name: "Salmon",
    servingSize: "100g",
    calories: 208,
    protein: 20,
    carbs: 0,
    fats: 13,
  },
  {
    id: "egg",
    name: "Egg",
    servingSize: "1 large",
    calories: 78,
    protein: 6,
    carbs: 0.6,
    fats: 5,
  },
  {
    id: "greek-yogurt",
    name: "Greek Yogurt",
    servingSize: "100g",
    calories: 59,
    protein: 10,
    carbs: 3.3,
    fats: 0.4,
  },
  {
    id: "tuna",
    name: "Canned Tuna",
    servingSize: "100g",
    calories: 132,
    protein: 29,
    carbs: 0,
    fats: 0.9,
  },
  // Carbs
  {
    id: "brown-rice",
    name: "Brown Rice",
    servingSize: "100g cooked",
    calories: 111,
    protein: 2.6,
    carbs: 23,
    fats: 0.9,
  },
  {
    id: "white-rice",
    name: "White Rice",
    servingSize: "100g cooked",
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fats: 0.3,
  },
  {
    id: "oats",
    name: "Oats",
    servingSize: "100g dry",
    calories: 389,
    protein: 17,
    carbs: 66,
    fats: 7,
  },
  {
    id: "sweet-potato",
    name: "Sweet Potato",
    servingSize: "100g",
    calories: 86,
    protein: 1.6,
    carbs: 20,
    fats: 0.1,
  },
  {
    id: "banana",
    name: "Banana",
    servingSize: "1 medium",
    calories: 105,
    protein: 1.3,
    carbs: 27,
    fats: 0.3,
  },
  {
    id: "whole-wheat-bread",
    name: "Whole Wheat Bread",
    servingSize: "1 slice",
    calories: 81,
    protein: 4,
    carbs: 14,
    fats: 1,
  },
  // Vegetables
  {
    id: "broccoli",
    name: "Broccoli",
    servingSize: "100g",
    calories: 34,
    protein: 2.8,
    carbs: 7,
    fats: 0.4,
  },
  {
    id: "spinach",
    name: "Spinach",
    servingSize: "100g raw",
    calories: 23,
    protein: 2.7,
    carbs: 3.6,
    fats: 0.4,
  },
  {
    id: "carrot",
    name: "Carrot",
    servingSize: "100g",
    calories: 41,
    protein: 0.9,
    carbs: 10,
    fats: 0.2,
  },
  // Fats
  {
    id: "olive-oil",
    name: "Olive Oil",
    servingSize: "1 tbsp",
    calories: 119,
    protein: 0,
    carbs: 0,
    fats: 13,
  },
  {
    id: "almonds",
    name: "Almonds",
    servingSize: "28g",
    calories: 164,
    protein: 6,
    carbs: 6,
    fats: 14,
  },
  {
    id: "peanut-butter",
    name: "Peanut Butter",
    servingSize: "2 tbsp",
    calories: 188,
    protein: 8,
    carbs: 7,
    fats: 16,
  },
];
